import Head from 'next/head'
import NavBar from '@/components/Navbar'


export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by Maren Aranburo" />
        
      </Head>
     <main className=''>
      Home
     </main>
    </>
  )
}
